### ISSUE TITLE
License

### ISSUE THREAD

**Issue by IzzySoft** [BlackIQ/whatsdone#2]
May I ask what license your app falls under? Without a proper license, it's not "free" (but means "all rights reserved"), which raises uncertainty for those who want to use the app or even contribute. If you're unsure, [Codeberg has a nice article](https://docs.codeberg.org/getting-started/licensing/) explaining it with easy terms, so you don't have to dive the jungle yourself.

**Comment by BlackIQ** [comment]
Hi Izzy,

Thanks for pointing me to this. Usually I use MIT or GPL but for this project, I really forgot to create.

May I ask you what your would prefer between GPL and MIT?
I saw that [Flulator](https://github.com/BlackIQ/flulator) dosn't have license too. Tell me which you suggest and I'll create for app.

Tnx alot.

Amir.

**Comment by IzzySoft** [comment]
Thanks for your fast response, Amir! As it's your app, it's rather a question of which you prefer – both are fine. I personally use GPLv2 or AGPLv3 (both make sure that derivative works stay under the same license, while MIT or Apache allow commercialization without publication of modifications, i.e. without "giving back").

If I may give another suggestion: Why not attaching the `*.apk` to its corresponding release? Makes it easier to find, and doesn't "bloat" your repo. What's inside the repo is pulled each time one forks/clones the repo, and 18M+ each release is probably much more than the code itself warrants for :wink: Further I just noticed Github seems to have limited its API – so I cannot automatically pull the APK out of the repo anymore.

For some background: I've just "adopted" your app into my repo, it [became available here](https://apt.izzysoft.de/fdroid/index/apk/com.blackiq.whatsdone) about an hour ago. Usually my updater takes care to fetch the latest APK whenever a new one became available. This works fine with APKs attached to their corresponding releases, but somehow fails for yours being fetched from inside the repo…

Besides, if you wish to link there, you can use [my badges](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) for that. Like [![badge](https://img.shields.io/endpoint?url=https://apt.izzysoft.de/fdroid/api/v1/shield/com.blackiq.whatsdone)](https://apt.izzysoft.de/fdroid/index/apk/com.blackiq.whatsdone) or

[<img src="https://gitlab.com/IzzyOnDroid/repo/-/raw/master/assets/IzzyOnDroid.png" height="75">](https://apt.izzysoft.de/fdroid/index/apk/com.blackiq.whatsdone)

```
[![badge](https://img.shields.io/endpoint?url=https://apt.izzysoft.de/fdroid/api/v1/shield/com.blackiq.whatsdone)](https://apt.izzysoft.de/fdroid/index/apk/com.blackiq.whatsdone)

[<img src="https://gitlab.com/IzzyOnDroid/repo/-/raw/master/assets/IzzyOnDroid.png" height="75">](https://apt.izzysoft.de/fdroid/index/apk/com.blackiq.whatsdone)
```

**Comment by BlackIQ** [comment]
Well, thank you very much. Tnx for adding this simple application to your platform.
Ok, first I will create a license. As you said, GPLv2.
Next, I'll put the APK file in a simple direct way. The current path is in `/docs/app/whatsdone.apk`. So let me create a new directory like `/app` then there will be the application.
For badges, sure! Will add theme too.

Did I forgot anything? Tell me to do them.
Tnx again.

Amir.

**Comment by IzzySoft** [comment]
> As you said, GPLv2.

Thanks, great! I'll set that here then as well.

> So let me create a new directory like `/app` then there will be the application.

That's still inside the repository and won't solve the issue mentioned. When you edit your release (to add the changelog etc) you can also attach additional files there. That's what I meant by "attaching it to its corresponding release". See e.g. [here](https://github.com/OxfordHCC/tracker-control-android/releases) for an example. Besides, that's where most project place the APKs (if they provide them), and where users look first normally as well :wink:

**Comment by BlackIQ** [comment]
Ok, I created the license. For APK in release, sorry I didn't understand it first. Ok let me have a new release tomorrow. I am going to fix small parts and have new feature. After I'll tell you.

Tnx.

Amir.

**Comment by IzzySoft** [comment]
> I created the license.

Thanks :green_heart: 

> For APK in release, sorry I didn't understand it first.

They say a picture speaks louder than a thousand words, so I let this screenshot speak:

![image](https://user-images.githubusercontent.com/6781438/143790519-2df75264-4d5e-468c-b91c-cad08fa735b7.png)

> Ok let me have a new release tomorrow. I am going to fix small parts and have new feature. After I'll tell you.

Great, looking forward to that! As for the tag name: currently you use `whatsdone-<versionName>`, which is fine. Please make sure to keep that pattern, as that's what my updater then will look for.

**Comment by BlackIQ** [comment]
Hi again,

I update the last release and add the binary file.

[Link](https://github.com/BlackIQ/whatsdone/releases/tag/whatsdone-1.0.0)

**Comment by IzzySoft** [comment]
Looks good, thanks! Please continue this way – and do not forget to increase `versionCode` (and adjust `versionName`) with future releases. I've updated the config on my end: if those criteria are met, new releases should be fetched automatically within 24h of your attaching the APK, so users should be notified by their F-Droid client.

Thanks once more for your swift reaction and corrections! Now that the APK is available at releases, I'd suggest you drop it from inside the repo and only update it to releases (keeps the repo slim and thus reduces resources needed when forking/cloning). As it looks like the issue was solved completely, I'd say we can close it; should you have any questions left, feel free to ask of course :wink:

**Comment by BlackIQ** [comment]
Thank you. Sure I will remove apks inside the repo. Tnx for pointing at.
